// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOBiERoXAacpA0qj4rpqL1qvlEQghnuvw',
    appId: '1:653087699319:web:7abb9268197efdf30cf172',
    messagingSenderId: '653087699319',
    projectId: 'tokende-e535e',
    authDomain: 'tokende-e535e.firebaseapp.com',
    storageBucket: 'tokende-e535e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7OyEHOhOfbb7vm0sbzUHoqy8spKYPXEk',
    appId: '1:653087699319:android:3ce0c3520cde3b850cf172',
    messagingSenderId: '653087699319',
    projectId: 'tokende-e535e',
    storageBucket: 'tokende-e535e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVKW47zSl3bUj8x20H-08DsG8C_BM2-rk',
    appId: '1:653087699319:ios:b8ad73e2ada1788f0cf172',
    messagingSenderId: '653087699319',
    projectId: 'tokende-e535e',
    storageBucket: 'tokende-e535e.firebasestorage.app',
    iosBundleId: 'com.example.transportInterurbainTokende',
  );
}
